### ISSUE TITLE
cd non-existent-directory

### ISSUE THREAD

**Issue by zdennis** [zdennis/yap-shell#2]
```
£ ~/source/mhs_projects/hendrick/autoguard-pricing-playground spike/vsc-2015-changes ➜ cd li
/Users/zdennis/source/playground/yap-shell/lib/yap/shell/builtins/cd.rb:8:in `chdir': No such file or directory @ dir_chdir - li (Errno::ENOENT)
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/builtins/cd.rb:8:in `block in <module:Builtins>'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/commands.rb:59:in `call'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/commands.rb:59:in `execute'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/builtin_command_execution.rb:6:in `block in <class:BuiltinCommandExecution>'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/command_execution.rb:20:in `instance_exec'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/command_execution.rb:20:in `execute'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/context.rb:62:in `block in execute'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/context.rb:44:in `each'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/context.rb:44:in `each_with_index'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/execution/context.rb:44:in `execute'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell.rb:49:in `block (2 levels) in repl'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:43:in `call'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:43:in `block in visit_CommandNode'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:174:in `with_standard_streams'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:28:in `visit_CommandNode'
	from /Users/zdennis/.rvm/gems/ruby-2.1.5/gems/yap-shell-parser-0.0.2/lib/yap/shell/parser/nodes.rb:5:in `accept'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:51:in `visit_StatementsNode'
	from /Users/zdennis/.rvm/gems/ruby-2.1.5/gems/yap-shell-parser-0.0.2/lib/yap/shell/parser/nodes.rb:5:in `accept'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:15:in `evaluate'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell.rb:46:in `block in repl'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/repl.rb:24:in `block in loop_on_input'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/repl.rb:12:in `loop'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/repl.rb:12:in `loop_on_input'
	from /Users/zdennis/source/playground/yap-shell/lib/yap/shell.rb:44:in `repl'
	from /Users/zdennis/source/playground/yap-shell/lib/yap.rb:61:in `run_shell'
	from /Users/zdennis/bin/yap:20:in `<main>'
```

**Comment by zdennis** [comment]
This has been resolved in the 0.1.1 version of yap-shell, specifically in this changeset: https://github.com/zdennis/yap-shell/compare/230598b...c1ed23b

When cd'ing to a non-existent directory this will now output:

```
yap> cd non-existent-dir
cd: non-existent-dir: No such file or directory
```
